const fs = require("fs");
const path = require("path");
const {
  CATALOG_DIR,
  CLAUDE_MD_FILE,
  FRAMEWORK_PACKAGE,
  LOCK_FILE,
  MANAGED_ROOT,
  STATE_ROOT,
  USER_CONFIG_FILE,
  VERSION_FILE,
} = require("./constants");
const {
  listExistingManagedFiles,
  normalizeRelativePath,
  readJsonIfExists,
  readTextIfExists,
  resolveRepoPath,
  writeRepoTextFile,
} = require("./fs");
const { sha256 } = require("./hash");
const { stableStringify } = require("./json");
const { version: FRAMEWORK_VERSION } = require("../../package.json");

function readCatalogText(relativePathFromCatalogDir) {
  const absolutePath = path.join(CATALOG_DIR, ...relativePathFromCatalogDir.split("/"));
  return fs.readFileSync(absolutePath, "utf8");
}

function catalogBaseDir(subdir) {
  return path.join(CATALOG_DIR, "claude-base", "claude", subdir);
}

// The managed set is derived from the catalog on disk, never hardcoded: a hardcoded list
// drifts from the catalog silently, which is how a baseline agent once shipped a wrapper
// pointing at a definition that was never rendered. Sorted for stable lock.json ordering.
function listCatalogMarkdown(subdir) {
  const dir = catalogBaseDir(subdir);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort();
}

function listCatalogSkills() {
  const dir = catalogBaseDir("skills");
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => `${entry.name}/SKILL.md`)
    .filter((relativePath) => fs.existsSync(path.join(dir, ...relativePath.split("/"))))
    .sort();
}

// A skill directory may carry more than SKILL.md (e.g. a harness-specific sidecar under
// agents/). Everything else in the directory is copied through verbatim, same as SKILL.md,
// just via a second, generic pass rather than special-casing each filename.
function listCatalogSkillSupportingFiles(skillName) {
  const dir = catalogBaseDir(path.join("skills", skillName));
  if (!fs.existsSync(dir)) return [];
  const collected = [];
  function walk(current, prefix) {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(path.join(current, entry.name), `${prefix}${entry.name}/`);
        continue;
      }
      if (entry.name === "SKILL.md" && prefix === "") continue;
      collected.push(`${prefix}${entry.name}`);
    }
  }
  walk(dir, "");
  return collected.sort();
}

function renderManagedFiles({ cwd }) {
  const repoName = path.basename(cwd);
  const managedAgents = listCatalogMarkdown("agents");
  const managedSkills = listCatalogSkills();

  const baseFiles = {
    [CLAUDE_MD_FILE]: `# ${repoName}

This repository uses a shared Claude Code bootstrap managed by ${FRAMEWORK_PACKAGE}.

## Working rules

- Treat \`.kyos/claude/\` as the managed source layer.
- Use \`.claude/\` as the repo-owned customization and override layer.
- Run \`npx kyos-cli --init\` to install or analyze the base structure.
- Review proposals from \`npx kyos-cli --init\`, then apply changes manually (or reset with \`--init --force\` if appropriate).
`,
    [normalizeRelativePath(path.join(MANAGED_ROOT, "skills", "README.md"))]:
      "# Managed Claude Skills\n\nThis folder is generated by kyos. Put repo-specific skills in `.claude/skills/`.\n",
    [normalizeRelativePath(path.join(MANAGED_ROOT, "rules", "README.md"))]:
      "# Managed Rules\n\nThis folder is generated by kyos as a managed source layer. Put repo-specific rules in `.claude/rules/`.\n",
  };

  for (const filename of managedAgents) {
    baseFiles[normalizeRelativePath(path.join(MANAGED_ROOT, "agents", filename))] = readCatalogText(
      `claude-base/claude/agents/${filename}`
    );
  }

  for (const filename of managedSkills) {
    baseFiles[normalizeRelativePath(path.join(MANAGED_ROOT, "skills", filename))] = readCatalogText(
      `claude-base/claude/skills/${filename}`
    );
    const skillName = filename.split("/")[0];
    for (const supportingPath of listCatalogSkillSupportingFiles(skillName)) {
      baseFiles[normalizeRelativePath(path.join(MANAGED_ROOT, "skills", skillName, supportingPath))] =
        readCatalogText(`claude-base/claude/skills/${skillName}/${supportingPath}`);
    }
  }

  return baseFiles;
}

// Direct-written metadata, not a checksummed managed file: --apply only writes
// "create"-action managed changes, so a stamp in the managed layer could never
// refresh on upgrade. Called on every init/update/apply.
function writeVersionStamp(cwd, repoName) {
  writeRepoTextFile(cwd, VERSION_FILE, stableStringify({
    framework: FRAMEWORK_PACKAGE,
    managedRoot: MANAGED_ROOT,
    repoName,
    version: FRAMEWORK_VERSION,
  }));
}

// Returns the recorded stamp, or null when none exists. A repo wired by a
// pre-stamp release has no version.json, which is how callers recognize an
// installation upgraded "from an unknown version".
function readVersionStamp(cwd) {
  return readJsonIfExists(resolveRepoPath(cwd, VERSION_FILE));
}

function loadLock(cwd) {
  const lockPath = resolveRepoPath(cwd, LOCK_FILE);
  return (
    readJsonIfExists(lockPath) || {
      framework: FRAMEWORK_PACKAGE,
      files: {},
    }
  );
}

function planManagedChanges({ cwd, desiredFiles, currentLock }) {
  const results = [];
  const finalLockFiles = {};

  for (const [relativePath, desiredContent] of Object.entries(desiredFiles)) {
    if (relativePath === LOCK_FILE) {
      continue;
    }

    const absolutePath = resolveRepoPath(cwd, relativePath);
    const currentContent = readTextIfExists(absolutePath);
    const currentChecksum = currentContent === null ? null : sha256(currentContent);
    const desiredChecksum = sha256(desiredContent);
    const lockEntry = currentLock.files ? currentLock.files[relativePath] : null;
    const lockedChecksum = lockEntry ? lockEntry.checksum : null;

    if (currentContent === null) {
      results.push({ action: "create", path: relativePath, content: desiredContent });
      finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
      continue;
    }

    if (currentChecksum === desiredChecksum) {
      results.push({ action: "ok", path: relativePath });
      finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
      continue;
    }

    if (!lockEntry) {
      results.push({
        action: "blocked",
        path: relativePath,
        reason: "unmanaged file already exists with different content",
      });
      continue;
    }

    if (currentChecksum !== lockedChecksum) {
      results.push({
        action: "conflict",
        path: relativePath,
        reason: "local changes detected; file was not overwritten",
      });
      finalLockFiles[relativePath] = lockEntry;
      continue;
    }

    results.push({ action: "update", path: relativePath, content: desiredContent });
    finalLockFiles[relativePath] = { checksum: desiredChecksum, managed: true };
  }

  return { results, finalLockFiles };
}

function applyManagedChanges({ cwd, plan }) {
  for (const item of plan.results) {
    if (item.action !== "create" && item.action !== "update") {
      continue;
    }

    writeRepoTextFile(cwd, item.path, item.content);
  }

  writeRepoTextFile(
    cwd,
    LOCK_FILE,
    stableStringify({
      framework: FRAMEWORK_PACKAGE,
      files: plan.finalLockFiles,
    })
  );
}

function findStaleManagedFiles(cwd, desiredFiles, currentLock) {
  const ignoredPaths = new Set([LOCK_FILE, USER_CONFIG_FILE, VERSION_FILE]);
  const desiredPaths = new Set(
    Object.keys(desiredFiles).filter((pathName) => !ignoredPaths.has(pathName))
  );
  const stalePaths = [];

  for (const pathName of Object.keys(currentLock.files || {})) {
    if (!ignoredPaths.has(pathName) && !desiredPaths.has(pathName)) {
      stalePaths.push(pathName);
    }
  }

  for (const rootFolder of [STATE_ROOT, MANAGED_ROOT]) {
    for (const pathName of listExistingManagedFiles(cwd, rootFolder)) {
      if (!ignoredPaths.has(pathName) && !desiredPaths.has(pathName) && !stalePaths.includes(pathName)) {
        stalePaths.push(pathName);
      }
    }
  }

  return stalePaths.sort();
}

module.exports = {
  applyManagedChanges,
  findStaleManagedFiles,
  listCatalogMarkdown,
  listCatalogSkills,
  listCatalogSkillSupportingFiles,
  loadLock,
  planManagedChanges,
  readCatalogText,
  readVersionStamp,
  renderManagedFiles,
  writeVersionStamp,
};
